version: '2'
services:
    myoauth-mongodb:
        container_name: myoauth-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb myoauth-mongodb-config
    myoauth-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    myoauth-mongodb-config:
        image: mongo:3.2.10
        container_name: myoauth-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
