version: '2'
services:
    myoauth-mongodb:
        container_name: myoauth-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/myOauth/mongodb/:/data/db/
